USE [master];

CREATE DATABASE [UABMSHIMCR]
CONTAINMENT = NONE
ON  PRIMARY 
( NAME = N'UABMSHIMCR', FILENAME = N'UABMSHIMCR.mdf' , SIZE = 133327552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
LOG ON 
( NAME = N'UABMSHIMCR_log', FILENAME = N'UABMSHIMCR_log.ldf' , SIZE = 24576KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UABMSHIMCR] SET COMPATIBILITY_LEVEL = 140;

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [UABMSHIMCR].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

ALTER DATABASE [UABMSHIMCR] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [UABMSHIMCR] SET ANSI_NULLS OFF;
ALTER DATABASE [UABMSHIMCR] SET ANSI_PADDING OFF;
ALTER DATABASE [UABMSHIMCR] SET ANSI_WARNINGS OFF;
ALTER DATABASE [UABMSHIMCR] SET ARITHABORT OFF;
ALTER DATABASE [UABMSHIMCR] SET AUTO_CLOSE OFF;
ALTER DATABASE [UABMSHIMCR] SET AUTO_SHRINK ON;
ALTER DATABASE [UABMSHIMCR] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [UABMSHIMCR] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [UABMSHIMCR] SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE [UABMSHIMCR] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [UABMSHIMCR] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [UABMSHIMCR] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [UABMSHIMCR] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [UABMSHIMCR] SET  DISABLE_BROKER;
ALTER DATABASE [UABMSHIMCR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [UABMSHIMCR] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [UABMSHIMCR] SET TRUSTWORTHY OFF;
ALTER DATABASE [UABMSHIMCR] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [UABMSHIMCR] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [UABMSHIMCR] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [UABMSHIMCR] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [UABMSHIMCR] SET RECOVERY SIMPLE;
ALTER DATABASE [UABMSHIMCR] SET  MULTI_USER;
ALTER DATABASE [UABMSHIMCR] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [UABMSHIMCR] SET DB_CHAINING OFF;
ALTER DATABASE [UABMSHIMCR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF );
ALTER DATABASE [UABMSHIMCR] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [UABMSHIMCR] SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE [UABMSHIMCR] SET QUERY_STORE = OFF;

USE [UABMSHIMCR];
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
ALTER DATABASE [UABMSHIMCR] SET READ_WRITE;

