USE [master];

CREATE DATABASE [TEST_MCR];

ALTER DATABASE [TEST_MCR] MODIFY FILE
( NAME = N'TEST_MCR' , SIZE = 133327552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB );

ALTER DATABASE [TEST_MCR] MODIFY FILE
( NAME = N'TEST_MCR_log' , SIZE = 24576KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB );

ALTER DATABASE [TEST_MCR] SET COMPATIBILITY_LEVEL = 140;

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    begin
        EXEC [TEST_MCR].[dbo].[sp_fulltext_database] @action = 'enable'
    end
GO

ALTER DATABASE [TEST_MCR] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [TEST_MCR] SET ANSI_NULLS OFF;
ALTER DATABASE [TEST_MCR] SET ANSI_PADDING OFF;
ALTER DATABASE [TEST_MCR] SET ANSI_WARNINGS OFF;
ALTER DATABASE [TEST_MCR] SET ARITHABORT OFF;
ALTER DATABASE [TEST_MCR] SET AUTO_CLOSE OFF;
ALTER DATABASE [TEST_MCR] SET AUTO_SHRINK ON;
ALTER DATABASE [TEST_MCR] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [TEST_MCR] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [TEST_MCR] SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE [TEST_MCR] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [TEST_MCR] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [TEST_MCR] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [TEST_MCR] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [TEST_MCR] SET DISABLE_BROKER;
ALTER DATABASE [TEST_MCR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [TEST_MCR] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [TEST_MCR] SET TRUSTWORTHY OFF;
ALTER DATABASE [TEST_MCR] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [TEST_MCR] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [TEST_MCR] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [TEST_MCR] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [TEST_MCR] SET RECOVERY SIMPLE;
ALTER DATABASE [TEST_MCR] SET MULTI_USER;
ALTER DATABASE [TEST_MCR] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [TEST_MCR] SET DB_CHAINING OFF;
ALTER DATABASE [TEST_MCR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF );
ALTER DATABASE [TEST_MCR] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [TEST_MCR] SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE [TEST_MCR] SET QUERY_STORE = OFF;

USE [TEST_MCR];
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
ALTER DATABASE [TEST_MCR] SET READ_WRITE;

